## Sword module configuration file

## Required elements
# Module Unique Identifier.
[STV]

# Short well known abbreviation for the module (e.g., [KJV]).
Abbreviation=STV

# Short description of the module.
Description=De ganse Heilige Schrift bevattende al de kanonieke boeken van het Oude en Nieuwe Testament

# Path to the module data files relative to the SWORD module library root directory.
DataPath=./modules/texts/ztext/stv/

# Driver used for reading the module.
ModDrv=zText

## Required elements with defaults
# Markup used in the module.
SourceType=OSIS

# How the text in the conf and in the module are encoded.
Encoding=UTF-8

# Compression algorithm.
CompressType=ZIP

# How much of the work is compressed into a block.
BlockType=BOOK

# Versification employed by a Bible module.
Versification=DutSVV

## Elements required for proper rendering
# Filters.
GlobalOptionFilter=OSISFootnotes
GlobalOptionFilter=OSISHeadings
GlobalOptionFilter=OSISScripref
GlobalOptionFilter=OSISLemma
GlobalOptionFilter=OSISStrongs

# Module features.
Feature=NoParagraphs
Feature=StrongsNumbers

## General informatic and installer elements
# A lengthier description.
About=\qc Bijbel\par\par Dat is\par de ganse Heilige Schrift\par\par bevattende al de kanonieke boeken\par van hetT\par\par Oude en Nieuwe Testament\par\par door last van de hoog-mogende heren Staten-Generaal der Verenigde Nederlanden en volgens het besluit van de synode nationaal gehouden te Dordrecht in de jaren 1618 en 1619 uit de oorspronkelijke talen in onze Nederlandse taal getrouwelijk overgezet.

# Module's revision.
Version=1.4
History_1.4=(2026-09-18) Verzen met een versgrens midden in de tekst alsnog gesplitst (63 psalmopschriften plus 1Kon 22:43, Neh 7:73, Joh 1:38, Rom 7:25, 3Joh 1:14, Openb 12:18); dubbel genummerd Ps 13:6 samengevoegd.

# Indicates what has changed between different versions.

# The minimum version of the SWORD library required for this module.
MinimumVersion=1.9.0

# Library of Congress Subject Heading.
LCSH=Bible .Dutch Flemish

# Language code of the module.
Lang=nl

## Copyright and Licensing related elements
DistributionLicense=Public Domain
TextSource=https://github.com/jajpater/statenvertaling

